public enum Type {
    COPY, ADD, SUBTRACT, MULTIPLY, DIVIDE,
    SQUARE_ROOT, SIN, COS, TAN, ASIN,
    ACOS, ATAN2, POWER, MOD, IS_EQUAL,
    IS_GREATER, NOT, AND, OR, JUMP_IF,
    PRINT, PRINT_NUMBERS, ITERATE, COPY_FROM, POINTER,
    POSITION, JUMP, END, FLOOR, ROUND,
    CEIL, TIME, NEW_LIST, COPY_FROM_LIST, LENGTH_OF_LIST,
    LIST_AMOUNT, ADD_LIST, REMOVE_AT_LIST, EMPTY_LIST, REMOVE_ALL_LISTS,
    ADD_AT_LIST, REVERSE_LIST, SHUFFLE_LIST, SORT_LIST, SLEEP,
    RANDOM, INPUT, LIST_SET, UPDATE_CONSOLE, PRINT_VECTOR,
    PRINT_VECTOR_NUMBERS, PRINT_VECTOR_SEPARATED, SET_COLOR, SET_POSITION, SET_TEXT_SIZE,
    DRAW_TRIANGLES, DRAW_TEXT, BEGIN_DRAWING, END_DRAWING, IS_PRESSED,
    MOUSE_PRESSED, GET_MOUSE_X, GET_MOUSE_Y, GET_SCROLL, GET_WIDTH,
    GET_HEIGHT, LIST_LOAD, LIST_STORE
}